# Generated by Django 6.0.6 on 2026-06-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
