# Generated by Django 6.0.6 on 2026-06-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_package_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
