# Generated by Django 6.0.6 on 2026-06-20 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#0B1E3D', max_length=10)),
                ('secondary_color', models.CharField(default='#C9A84C', max_length=10)),
                ('company_tagline', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branding Settings',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smtp_host', models.CharField(blank=True, max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(default='noreply@ybs.in', max_length=254)),
                ('from_name', models.CharField(default='YBS', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='YBS', max_length=200)),
                ('company_email', models.EmailField(default='info@ybs.in', max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_address', models.TextField(blank=True)),
                ('company_website', models.URLField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=200)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=200)),
                ('razorpay_enabled', models.BooleanField(default=False)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=200)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=200)),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
            },
        ),
    ]
