# Generated by Django 6.0.6 on 2026-06-17 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('due_date', models.DateField()),
                ('category', models.CharField(choices=[('GST', 'GST Return'), ('TDS', 'TDS Return'), ('ROC', 'ROC Filing'), ('PF', 'PF/ESI'), ('ITR', 'Income Tax Return'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('notified_30', models.BooleanField(default=False)),
                ('notified_7', models.BooleanField(default=False)),
                ('notified_1', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('ORDER_UPDATE', 'Order Update'), ('MILESTONE', 'Milestone Update'), ('PAYMENT', 'Payment'), ('COMPLIANCE', 'Compliance Deadline'), ('DOCUMENT', 'Document Request'), ('REFERRAL', 'Referral'), ('PROMOTIONAL', 'Promotional'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_order_id', models.UUIDField(blank=True, null=True)),
                ('related_invoice_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
